[project]
name = "biesnes_app"
authors = [{name = "Lev", email = "levdobriy2012@mail.ru"}]
version = "1.0.0"
requires-python = ">=3.11"
dependencies = [
    "tkinter"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "sqlite3"
]